GOCMD=go
GOBUILD=$(GOCMD) build
GOCLEAN=$(GOCMD) clean
GOTEST=$(GOCMD) test
GOGET=$(GOCMD) get

OUTDIR=./out/
OUT_MAC=$(OUTDIR)mac_64/
OUT_WIN=$(OUTDIR)win_64/

BINARY_PATH_RUNTIME=$(OUT_MAC)SuddenlyMuscleTrainer
BINARY_PATH_RUNTIME_WIN=$(OUT_WIN)$(BINARY_PATH_RUNTIME).exe
BINARY_PATH_SETTING=$(OUT_MAC)SettingTool
BINARY_PATH_SETTING_WIN=$(OUT_WIN)$(BINARY_PATH_SETTING).exe


RUNTIMEDIR=./runtime
GUIDIR=./gui

all: build
build:
	$(GOBUILD) -o $(BINARY_PATH_RUNTIME) -v RUNTIMEDIR
	$(GOBUILD) -o $(BINARY_PATH_SETTING) -v GUIDIR
	CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 $(GOBUILD) -o $(BINARY_PATH_RUNTIME_WIN) -v RUNTIMEDIR
	CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 $(GOBUILD) -o $(BINARY_PATH_SETTING_WIN) -v GUIDIR
test:
	$(GOTEST) -v ./...
clean:
	$(GOCLEAN)
	rm -f $(BINARY_PATH_RUNTIME)
	rm -f $(BINARY_PATH_RUNTIME_WIN)
	rm -f $(BINARY_PATH_SETTING)
	rm -f $(BINARY_PATH_SETTING_WIN)
run:
	$(GOBUILD) -o $(BINARY_NAME) -v ./...
	./$(BINARY_NAME)
